import { describe, expect, it } from 'vitest';
import { classifyPath, inspectContent, safeRelativePath } from '../src/indexing/filter';

describe('classifyPath', () => {
  it.each([
    ['src/server.ts', 'CODE', 'typescript'],
    ['src/types.d.ts', 'CODE', 'typescript'],
    ['app/page.tsx', 'CODE', 'tsx'],
    ['lib/index.mjs', 'CODE', 'javascript'],
    ['components/Button.jsx', 'CODE', 'javascript'],
    ['next.config.js', 'CODE', 'javascript'],
    ['README.md', 'DOC', 'markdown'],
    ['docs/guide.mdx', 'DOC', 'markdown'],
    ['LICENSE', 'unsupported-type', undefined],
    ['README', 'DOC', 'text'],
    ['package.json', 'CONFIG', 'json'],
    ['apps/web/tsconfig.build.json', 'CONFIG', 'json'],
    ['Dockerfile', 'CONFIG', 'dockerfile'],
    ['docker-compose.prod.yml', 'CONFIG', 'yaml'],
    ['prisma/schema.prisma', 'CONFIG', 'prisma'],
    ['.env.example', 'CONFIG', 'text'],
  ])('%s → %s', (path, kindOrSkip, language) => {
    const result = classifyPath(path);
    if ('skip' in result) expect(result.skip).toBe(kindOrSkip);
    else expect(result).toEqual({ kind: kindOrSkip, language });
  });

  it.each([
    ['node_modules/react/index.js', 'ignored-directory'],
    ['packages/ui/dist/index.js', 'ignored-directory'],
    ['.next/server/app.js', 'ignored-directory'],
    ['src/__snapshots__/a.test.ts.snap', 'ignored-directory'],
    ['package-lock.json', 'lockfile'],
    ['pnpm-lock.yaml', 'lockfile'],
    ['public/app.min.js', 'minified'],
    ['static/vendor-bundle.js', 'minified'],
    ['src/server.js.map', 'source-map'],
    ['public/logo.png', 'unsupported-type'],
    ['src/main.py', 'unsupported-type'],
  ])('skips %s (%s)', (path, reason) => {
    expect(classifyPath(path)).toEqual({ skip: reason });
  });
});

describe('inspectContent', () => {
  const code = { kind: 'CODE', language: 'typescript' } as const;
  const inspect = (text: string, bytes = Buffer.from(text)) => inspectContent(bytes, text, code);

  it('accepts ordinary source', () => {
    expect(inspect('export const a = 1;\n'.repeat(500))).toBeNull();
  });

  it('detects binary content', () => {
    expect(inspect('abc', Buffer.from([0x61, 0x00, 0x62]))).toBe('binary');
  });

  it('detects generated files from their header', () => {
    expect(inspect('// @generated by protoc\nexport {}')).toBe('generated');
    expect(inspect('/* DO NOT EDIT: auto-generated */\nexport {}')).toBe('generated');
  });

  it('only looks for generated markers near the top', () => {
    expect(inspect(`${'const a = 1;\n'.repeat(10)}// do not edit this block\n`)).toBeNull();
  });

  it('detects minified code without a .min suffix', () => {
    expect(inspect(`var a=1;${'b(),'.repeat(2_000)}`)).toBe('minified');
  });

  it('does not treat long markdown lines as minified', () => {
    const doc = { kind: 'DOC', language: 'markdown' } as const;
    const text = 'word '.repeat(2_000);
    expect(inspectContent(Buffer.from(text), text, doc)).toBeNull();
  });
});

describe('safeRelativePath', () => {
  it('normalizes harmless paths', () => {
    expect(safeRelativePath('src/./a.ts')).toBe('src/a.ts');
    expect(safeRelativePath('src//a.ts')).toBe('src/a.ts');
  });

  it.each(['../etc/passwd', 'src/../../x', '/etc/passwd', 'C:/x', 'a\\b', 'a\0b', '', '.'])(
    'rejects %j',
    (path) => {
      expect(safeRelativePath(path)).toBeNull();
    },
  );
});
